---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1ke0cxfxawre9ps0d2h0ez43um25qk4gk6wfdg9s8a28pmxwlmcdqtwekph"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1ke0cxfxawre9ps0d2h0ez43um25qk4gk6wfdg9s8a28pmxwlmcdqtwekph"
