---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minio
spec:
  interval: 60m
  chart:
    spec:
      chart: minio
      version: 5.3.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 60m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2024-11-07T00-52-20Z
    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2024-11-17T19-35-25Z
    mode: standalone

    existingSecret: minio-secret

    # users:
    #   - accessKey: ${SECRET_VOLSYNC_MINIO_ACCESS_KEY}
    #     secretKey: ${SECRET_VOLSYNC_MINIO_SECRET_KEY}
    #     policy: readwrite
    #   - accessKey: ${SECRET_CNPG_MINIO_ACCESS_KEY}
    #     secretKey: ${SECRET_CNPG_MINIO_SECRET_KEY}

    persistence:
      enabled: true
      existingClaim: "nfs-minio-pvc"

    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - &api-host s3.${SECRET_DOMAIN}
      tls:
          - hosts:
              - *api-host
            secretName: s3-tls

    consoleIngress:
      enabled: true
      hosts:
        - &console-host minio.${SECRET_DOMAIN}
      tls:
          - hosts:
              - *console-host
            secretName: minio-tls

    securityContext:
      enabled: false
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 1500Mi
    metrics:
      serviceMonitor:
        enabled: true
