apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
stringData:
    #ENC[AES256_GCM,data:LGpEUg==,iv:IoIYpalkXEpq4TcsqjEhIs7glNX+Ag9VQj4gQ/46XlQ=,tag:4nphNr//34UkNFtsTPGGsg==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:L4QsVO/yIDag67rPnGaJEYkQaFDZPRmW0Gy1RYBqYuk9/voxFOOonhMhez60YpUtK9hvCauZm6Xjf/OdNaaYKWAgjdY42gXDULShscMx/+C2K+2NfQ==,iv:gL0AvxBhII7G9znNBIZgYwThJWaMXPdA9DALgomuUiY=,tag:Gil+YzCvFi0EKyot+FthMQ==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:8LRqpBnGTV2neKdDdPOOB+FKl+4FUEZqbdFoGIF8wjwi,iv:FN2J0CqxCEk/VUODuiiW+Hvb9ODoaQMSlIJk1ZFddAc=,tag:xduORA6nzUmjqEl53hxTcw==,type:str]
    LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:ycGq+IDssBzCIrwuS1CLESI=,iv:q4RZc0LLpsxlIxsjVsJkMdGvU6jfngouGJDX9agvPpI=,tag:gEVRrsyfwE6WbHWZMkZQCQ==,type:str]
    LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:pd3J31oDPe7/JCFH1mnLp/zCNUIN+rC97zMOxpyZ0E4BCfP+ZBAnHAoEMshIypph0tlvrDPM4y0oSAgpJXRK4m9BAnM9RVPDsY1Q+xYnGmIfSl4MjQizg7QTE9Z0MDfjluw=,iv:lTx8p1jBfKaTn7wt2aLAMbTtZX6TDu4lEfH+xb5allk=,tag:TJUOSWCBjs/Lwq6z9RVITg==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:+wwzjkM63kVW3HhynPgn4oNydW+8PXTEs4RwTuyHTC1JuQjkrrUCFAJg7Nbbqe0lhAoaIZQ6A9Zf8om0M61NPt6u6aCGa1zN5/6ShiVfKbKd4nfNPlPP5AtNtZcwbOOLmBZrAyStc2fxL/8=,iv:w5rttOrCoid4Pcagp50sXVPkWF44EsL0dkhoCtqZQHM=,tag:esx8Z/XPl5Uhc1gxD9fA4A==,type:str]
    #ENC[AES256_GCM,data:IH+G20oQROv/c2hCpx0=,iv:xoB4m9H1tuIovAeuSGzCp/flmpi5fx1zMZmO/iAqt6I=,tag:USW56lEKht046UwLjNLFLA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Qdxs3RM=,iv:wThqepqGJDGBqly0jadDb8YQcY2KEZaPbNppKnrITqs=,tag:77oa730M2eBqvMamIfHt/g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:11RDC/DH8n745RhlNa5+q/LlmzouWUohA7jariRpy6SbeGkW,iv:JERb/VgkBq5bEIaV7A2NnhFcETNg3gwRXcZfQyf8AiQ=,tag:95+GekpuBqpOjVgvy7/DpQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:MGSZeFc=,iv:ZbZj3gv4+v/17QTynb6SjSBf3gIYFwtxZlIzqBuFcOw=,tag:+dxnp+++5/OxSK6mbWPu9w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:e5uveoLGjVOEnWhA0X+GV5pYd0zLIlDMO2YHkmBLcRPvoqFtRs4DwR3J7Uqpgmo=,iv:6MAHeGL9gG5fYv6Bh41DMMCKYvtuu+scShWTdOvK0Eo=,tag:Q6hlRm+f6BOTlKkzuh/UpA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:b56Nblk5yMCKfJSZQ2Wo+FBojFRtcm78nzzrPUpRYyDdq5xhpBOJ0Awwo0UMQU0=,iv:4GrgKciatR3ohSAOoPbFx9CEEnAMLAFzS1B+/Svv2Lk=,tag:fq0q1GdfLKeKRLNSW5Jbsg==,type:str]
    #ENC[AES256_GCM,data:1fNAc+c=,iv:leuLWVbRD9D11nnBwRlG8EgS6C6pi9sF7We3d+wRkKQ=,tag:xfMVBGMrszNr2871Of9oOg==,type:comment]
    LLDAP_SMTP_OPTIONS_SERVER: ENC[AES256_GCM,data:o9t3MHrZyxKUrO1ZNLD3DQ==,iv:ETArovgV3EX/gbYE8hGc2K4x7QEPEIp5n4Lds5gVtCs=,tag:/hSd4aCOFnDr+oNlmUittg==,type:str]
    LLDAP_SMTP_OPTIONS_PORT: ENC[AES256_GCM,data:m/Ul,iv:2St6vLXWMm7kJNBolGjd172l1aqVKeKWrIJ/T2MfxEQ=,tag:zTt6C9wqJG18Tzt2UMXkjg==,type:str]
    LLDAP_SMTP_OPTIONS_USER: ENC[AES256_GCM,data:XIj+MJQ5GnQCQFivZImbHlH6IUCt,iv:/V32zJ4IHEyBOr96M6XkcGX4Itz9ojv9g6kAS70r3lI=,tag:6hJinohnIqwn4JwgXkvFgw==,type:str]
    LLDAP_SMTP_OPTIONS_PASSWORD: ENC[AES256_GCM,data:9FpqE+x30g/WkgfBzQdhDC9sVQ==,iv:ingPRPCsfdVl35X8f5jZwr9rUbBNfc0uycvTogy45lg=,tag:yYmoXMKoj9t46m0PFoazpg==,type:str]
    LLDAP_SMTP_OPTIONS_FROM: ENC[AES256_GCM,data:Yq3nUMnWOorLYTy1RjRTR7loMmV8/3yO1/rC2vBQPyDH,iv:3wUC7Adnle9ICr4oGSP5xY7rcpyOPzuYwkkiIaa2KjY=,tag:yO7XKK6KtX9ue+pqe3jsFA==,type:str]
    LLDAP_SMTP_OPTIONS_REPLYTO: ENC[AES256_GCM,data:mbYRpotCyvIg5A6NU74HaeelnB9ied9gn38y2a0qNNbs0Q==,iv:0on3qc+wVzbrKAqbTzOCoqCqzd4gg56x27edoeT1aX4=,tag:nC6+1ng4vUdPS9OD39/17A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ke0cxfxawre9ps0d2h0ez43um25qk4gk6wfdg9s8a28pmxwlmcdqtwekph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa0RxbUxLYk9acVk3RWdN
            UWZGcTU2RzNQRWtCck9nSFErNHdzQi8xTUhBCjQ2b1hyNlNucW1qaFB2WEQvUVBk
            anJYRWNRTkcza2ZTNTNXbzhza3lENVUKLS0tIFprWXFzM0U5dGNLOVhON1IwdHRJ
            NW94RkJneVp6NTFUZ2RyMGM2MjlZa0kKKN9bNbaSZPGJcQyPAutySGby75Xh1u2Z
            6j3kX0fEwkJmdA2KOr/9tgvRGZ8tArxJyf3jst6iSfP0zu7Izk0pzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T00:33:08Z"
    mac: ENC[AES256_GCM,data:7zw/qqujl569kZLnRtxp+q+pB/4yYCaRDUt1GVpgHTEuA1qZPhuRR3EtLLNZPIzhRdf8gXB4CuZsKbEsRlFfE15efa+09WXaiEWXIO1xNQOyU0cStxErfc1kK+QvYfP+p55Ctt7GKMtffYpA15Pnvf44STOQhXUc4VMxKWI2u4M=,iv:Cr9k0D+aJQiffoETt6jXgCW7gQjZYj7qGHLsQJKh7d4=,tag:pxHuCp4PmTKyWQt9p66XdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
