---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-upgrade-controller
  namespace: flux-system
spec:
  targetNamespace: system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/system-upgrade/system-upgrade-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app system-upgrade-controller-plans
  namespace: flux-system
spec:
  targetNamespace: system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/system-upgrade/system-upgrade-controller/plans"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: system-upgrade-controller
  postBuild:
    substitute:
      # renovate: depName=ghcr.io/siderolabs/installer datasource=docker
      TALOS_VERSION: v1.8.4
      # renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
      KUBERNETES_VERSION: v1.32.0

      SCHEMATIC_ID: 613e1592b2da41ae5e265e8789429f22e121aab91cb4deb6bc3c0b6262961245
