---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: flux-system
spec:
  targetNamespace: dbms
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/databases/cloudnative-pg/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app-cluster postgres-cluster
  namespace: flux-system
spec:
  targetNamespace: dbms
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app-cluster
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/databases/cloudnative-pg/clusters"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: cloudnative-pg
    - name: longhorn
  postBuild:
    substitute:
      APP: *app-cluster
