apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./postgres-cluster.yaml
  - ./loadbalancer.yaml
  - ./scheduled-backup.yaml
  # - ../../../../templates/gatus/guarded
