apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:g50daa/5wV9h9s/d4kMS1giYrtBB7Jik4uA/4Qp1g9HodUNOUfSyQw==,iv:lqhsmL7Cv3e7fEoGcUsxscIb3z8QDJEC24du5X1NeUs=,tag:GE8dRvhBt4lKRmqtqNfZkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ke0cxfxawre9ps0d2h0ez43um25qk4gk6wfdg9s8a28pmxwlmcdqtwekph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS0srNW9wVTNTdVN2NFVF
            S0xKeGJySFlIOXZlalJIdDIvS1poZXFxRncwCjRiM2dQQWxKSitqYThQMVdKL3lj
            WmxwOFp3VmZkVHNSakdTdlI5YnJxaGsKLS0tIFhVdUNwTmt4VkNZQVN6UDRWb1NY
            UzQxbnNJL0tEQ1llcm43NTlBVWZjdzQKG68MyLRZnBY4sB7i4IhAQZtaYzr47UPY
            FKwDlZPN1A0KzdXbUQAAOvRdIF0e7La4cfC6heb+bLYLKv1kmPfHSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T18:15:45Z"
    mac: ENC[AES256_GCM,data:O2ur3V9hJtDR2Q8M1u1/gG4MAbbsHIsdap4G10sVDxQpJQdiVmBaUnoKKf06cPTv2qzTKl3RFjW/VWBJb3xM3U2+17lamrn9C9a8BGMa+xbaw+FjoY9vdAKED0eu1RpQyqHZENOYWbc4nRRplDED3keO8Ckwv5fNUwjPIF7hjxw=,iv:IUwjlcmWXSqkTn/g+6WDzh9UZZ0/XyBkxRZ0upZPOoM=,tag:00y41DDh017owJp1w3d77w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
