---
apiVersion: storage.k8s.io/v1
kind: StorageClass
reclaimPolicy: Delete
provisioner: driver.longhorn.io
parameters:
  # we set this to 2 replica for less copies of the cache, which can be blown away safely.
  dataLocality: disabled
  numberOfReplicas: "1"
  replicaAutoBalance: best-effort
  staleReplicaTimeout: "30"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
metadata:
  name: longhorn-cache
---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  name: longhorn-snapshot
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap  # a CSI snapshot maps to a Longhorn snapshot
