apiVersion: v1
kind: Secret
metadata:
    name: emqx-secret
stringData:
    admin_password: ENC[AES256_GCM,data:HaLPjiRXm8gUtQAke+QbvMln3s8guPtt9KfP1Vl+OQdXtTmxZk7UsalsovjX1HVVpR9I38hKSmYuv9I=,iv:cbGnV2STXlxX+DLQKkwXUu7/FnIOHQFeHM21lSn2OIU=,tag:YmjMGAamdOs5r4BXncg5FA==,type:str]
    user_1_password: ENC[AES256_GCM,data:HBl9fao+TZYhIm55m/mkYrU5t51i07sfhKdn1uklijcgzmw=,iv:TyXN2nEXOmGMhQzTExBiyodzm44dc4lsuqjo5db4LMY=,tag:P1Up01/ZHtFtAf9R0fn84w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ke0cxfxawre9ps0d2h0ez43um25qk4gk6wfdg9s8a28pmxwlmcdqtwekph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaHFnM1RhYkZONTBvbWNW
            SFNQVVhtbHZ2ZHVDTnRMblNUeEwzZEkxa1ZvCmFxT1VCM0swYUhPOHRWUklxZ2pE
            Y0p3a0JINml0TlRHY243eFFyQ2NjTzgKLS0tIFM1MTBoVE8xa0hwSmMxZ3Y4M0kx
            Y3cva0Zvd1MwMmRKTjg4dE9tUFJHcG8KSb0F97bcf1+aQHbsKdlCtZVNU/O5pTNU
            h1mLM8Q7yTkYDRQ3TZ61YZraohVerXpJI1wT13QkwtkKNhHONxdatA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T21:48:24Z"
    mac: ENC[AES256_GCM,data:nQZQyWLCJFzzgOwo4N9VAfE9iwrDZenl7aE3GBxhYXUtuC8KgEOd5BWALhBWyxyYB6H4EDwfApa2OPU1EpL1A9FNOVLuuVqrt9WUcLXEFRl8pUqRj+C4fY5mTvLRPq2tbbgjD0cEwycYR6RxxZvaaR79hvU5L08sgvxFzSK0dLw=,iv:FK8FofvnJJ4ewQu+Zn619R5nLNqAIfSMgv2eR3dc4ag=,tag:Gf7uQwWK0Jhv4LAUKaZj2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
