apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pihole
stringData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: ENC[AES256_GCM,data:urGGk7YeoAw=,iv:WpQIxPvrHzfMhPu/cVtKi4foTdFUwuH49Nt3//D9QSQ=,tag:wkhxLYq0PIZp0QqtyD/pIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ke0cxfxawre9ps0d2h0ez43um25qk4gk6wfdg9s8a28pmxwlmcdqtwekph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBT1IwVThFRTl1MFdDREEw
            MFRRdmFpb3NjQXZpOGVGV1lLZUhsM2REcDJRClkrNHZvOTFTQ01SSWh4cjZBd29Q
            S0hrZEcrdmdzMGliN2hwQUxyV1RFMmcKLS0tIDJWNE9yYXdQeEZhNEJ4NUlWcVo2
            V0h1NkhJaHVnVUY2TjMrOU1NSFphTkUKfwvlJdlDchEmEg9MHnJ+PfsS5mgO+u5j
            qU1rTiTCel8x9u+8lkjB1uNFSr8RaGdHKpr9Ym9LaK6EXt9tHN4VjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-18T21:19:04Z"
    mac: ENC[AES256_GCM,data:fVtq101zKRvdOmhQZjCfuKpzXi84BpJZTsJeVNFsey+vcaJDJ/tGCzPkmxQAltI4r9tDwLWy4SSwhflLTiJMTzJucSEj5DIGZBZcjciSDGRJpNGnzdlCimnwhgGAPVbZ33kxCWewaptooMKQVQ6Kssv7thH6nxXTZICXFaavHHA=,iv:E6ekciRgpZAkvzNkLRKfAsXxFgkRnR5NS8sbmCj9kE4=,tag:z0E0CK4mILU7w0mET10BFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
