---
authentication_backend:
  ldap:
    address: ldap://lldap.auth.svc.cluster.local:5389
    implementation: custom
    timeout: 5 seconds
    start_tls: false
    base_dn: dc=home,dc=arpa
    additional_users_dn: ou=people
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_search_mode: filter
    user: uid=authy,ou=people,dc=home,dc=arpa
    attributes:
      username: uid
      display_name: displayName
      mail: mail
      group_name: cn

session:
  name: authelia-home-ops
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - name: authelia_session
      domain: ${SECRET_DOMAIN}
      authelia_url: https://auth.${SECRET_DOMAIN}
      default_redirection_url: https://${SECRET_DOMAIN}
  redis:
    host: dragonfly.dbms.svc.cluster.local
    database_index: 2

notifier:
  disable_startup_check: true
  smtp:
    subject: '[Authelia] {title}'
    disable_require_tls: true

duo_api:
  disable: true

access_control:
  ## Default policy can either be 'bypass', 'one_factor', 'two_factor' or 'deny'. It is the policy applied to any
  ## resource if there is no policy to be applied to the user.
  default_policy: two_factor
  networks:
    - name: private
      networks: [10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16]
    - name: vpn
      networks: [10.10.0.0/16]
  rules:
    # bypass Authelia WAN + LAN
    - domain:
        - auth.${SECRET_DOMAIN}
      policy: bypass
    # One factor auth for LAN
    - domain:
        - "*.${SECRET_DOMAIN}"
      policy: one_factor
      subject: [group:admins, group:users]
      networks:
        - private
    # Deny public resources
    - domain: ["navidrome.${SECRET_DOMAIN}"]
      resources: [^/metrics.*$]
      policy: deny

