---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts/
      chart: app-template
      version: 3.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mealie:
        strategy: Recreate

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: *app

        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.3.0
              pullPolicy: IfNotPresent
            envFrom: *envFrom # All values are created on the externalsecret

    service:
      app:
        controller: mealie
        ports:
          http:
            port: &port 9000

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Mealie
          gethomepage.dev/icon: mealie.svg
          gethomepage.dev/group: Home
          external-dns-pihole.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: mealie-tls

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
