apiVersion: v1
kind: Secret
metadata:
    name: mealie
stringData:
    #ENC[AES256_GCM,data:BGKF8fCVFxdF+C1+Les=,iv:yKkuw54m5iWHOvMAbbpk32B3eVlvzR0z/+81ghDuXLM=,tag:SYVb0a6VNl1ttREawgCK8w==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:8nRb/QSH,iv:g44U7ouBDSYwI4tc+Cq17oA0rMmuxCavUXXnpNKPrbQ=,tag:cw6OTeVA3Iq8ZwW3djw43w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:SpL5IvbBfTpPI+6ri1loYxShSDSMJf8h8Pioje3zH/lsksBB,iv:z44cw4S44l1QcwfGHypck3EBcAbBoyRBmQv9jhE+gTE=,tag:TFgrjfLi+7xCQFLunIzitQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:0wSDmog=,iv:Dv0NSGpAifjjXBaPpabG7Nifyt0OaOXoZO+aa5JH8ZM=,tag:bYXF9y6kTjal1MhhxJyMLQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:rjGfUBcK8z+1Ufv/ednCedaJn4d/yyieI7aJhBSfCj442PBpl/OM+2kCJXr/KN0=,iv:WY7bwDMrWCQ7sXyqZwG4Xm8LUqlp7Z8HSNblKecs9hs=,tag:Kf/sCTay+Hx2cIEIQDgD1w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:bueqjNeflug8rO7cPS6a7EMmCBzExO1xS2WdhE8M+jQbTG5qSnEGMmyctpHILDU=,iv:QkoVdE4k3FWcPdAjvERjyMiDmwsLLpESDET3EjCpl60=,tag:7brsAE12KKmf6vusQvYboQ==,type:str]
    #ENC[AES256_GCM,data:DkZG9g==,iv:skuej6MrusmmJo6gQSDz2krIQ6ie1uF6RiH6x1RSGh0=,tag:Fb2akwxa8XxISW62E7YIfQ==,type:comment]
    POSTGRES_USER: ENC[AES256_GCM,data:pluk8/s=,iv:PMrbCWmWjunPeZf1TtgU/WmKzl2lWxpVXei89kT8XfM=,tag:D277466Hqf7+Zl7kfWDpdQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:51Ui+nnZgSm/e1qw9YV4W9q4U3jSndBHwpbpuNFDIW+trGmJ9tNHgUoaK6mj5ZA=,iv:s6iShPSC4WYFx4ctdlbnQ+5wi+DD5lPzyXI5jrTx68Y=,tag:jKS5IJtamtqzySBkFAjR9g==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:AKQ9f0O2dMl1ChLt1gamyu41TB/L16WGpdPgEi9oZFkSSIHe,iv:mfODtR+ie9s0Ea90nvva3SUbSw5VIq4n8MgdIP4z/JI=,tag:4jRVyzSYP3M6pYzX42BJCw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:UQoiQg==,iv:boeXTL22kkQO8TsMH1Mp4DMW79oCEZ1oiv6LVrcKOHM=,tag:uhiWLQVEv7So6aUaA7opVw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:2LZrToz5,iv:9s1BCPwZ6uWptaXUsoGGKVavc8EuMgcmz8+1jijc0eY=,tag:KfRTAxqNQT3Je1OSZTV3ww==,type:str]
    DB_ENGINE: ENC[AES256_GCM,data:bDoLAKwJQGQ=,iv:YZ8rY7f3IprNAj6RZD+1u81RLLklSjpb580XxqhX7cI=,tag:8DbB9AKlGSLnQhg9Q94fnw==,type:str]
    #ENC[AES256_GCM,data:M8DQVWuMUtXtZ56+,iv:9MToh0QOSgUe9l8ymBGbsm1fh7hwTBMx/0vSRa1XxgY=,tag:A4af9RLTovAYjWVim9n39g==,type:comment]
    BASE_URL: ENC[AES256_GCM,data:YmB/1SWRJH7i6BoWCU0ZtEClZFfU6IL3235C+ua58w==,iv:WS4oAOVThZ8JvjFaKbq4gbtIBC/mGv/goIrxhhhvkDk=,tag:8baIeWvO4AFw08uI2Vb3+Q==,type:str]
    ALLOW_SIGNUP: ENC[AES256_GCM,data:oLR2HN0=,iv:8RDnguChfcmlaQqP2qQxMc4xIgujuP76iaL3na07vIA=,tag:YinEt6v46B9EhJRbGTJJBw==,type:str]
    AUTO_BACKUP_ENABLED: ENC[AES256_GCM,data:bRYPXw==,iv:tVkzBStyg+JNUjk4EzP156pw1chBwfw1cxwnF9A/wos=,tag:KBnGsWBu9AyyymPrAaoxbA==,type:str]
    API_DOCS: ENC[AES256_GCM,data:91QU88w=,iv:5gKJYkYgc30MlhX5TUzJUyBCqNVtCe+iyfRPI8Rz6mY=,tag:WCvKllDttV+QWVBe1+X1Hg==,type:str]
    TZ: ENC[AES256_GCM,data:KIERnts=,iv:dlc+olwKzdF/50UsxyDOIM6T2cMw0Czequ6xjJLnjnk=,tag:9GAVclvy4rUqYB0exqX5Yw==,type:str]
    WORKERS_PER_CORE: ENC[AES256_GCM,data:XA==,iv:jnEaAp4E2L1Tn6w1s3I8x8o423fsNH2bHMKPdZ5ySik=,tag:Mgln6wrz0ivWHe692E7seA==,type:str]
    MAX_WORKERS: ENC[AES256_GCM,data:dg==,iv:ZujaV2KA0UWfZhoo9db10+dY5OdWsEtcUUMwlncjlo8=,tag:Vt4lf8bPGv1c924IfyG3Fg==,type:str]
    WEB_CONCURRENCY: ENC[AES256_GCM,data:Rw==,iv:fmvoAHMS6foeqfLOdJx14i3ajnvMANaGFzSiC5TMKsY=,tag:ZKmx6siOiHpUrflLao+GhA==,type:str]
    #ENC[AES256_GCM,data:CGcO7PI=,iv:h3GZLaxsRkKJipEisKUm9NhLctDOY9LwSKDfb4R58Og=,tag:BJG0xze/nbye3sXhgokNjA==,type:comment]
    SMTP_HOST: ENC[AES256_GCM,data:7w0QlKRX2KC6W0RmUnN6Jw==,iv:VeJNYNjDOLOyFLjAh0X4HnrjlV7Bm2BH+uhRnWvpgZY=,tag:W0JlhK5gNgsAzR2/ossTBA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:lYRE,iv:3M05kPpOmEoYaKcrAbs2FZTuEQrdfKzXqrrMPbSYSFI=,tag:e3VtdBns74F6VHKA9DPzbw==,type:str]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:xl6kXcMNye5P3Fvw,iv:mUmy73vXe8kjY5B1Flo42qLopDJkZZCsNm4rfcPiHY4=,tag:byAUOdElUeoIVtcAOCUn9g==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:r7qu,iv:lEAn0MyzCEcoOgB9NmrdaWpA5ikLEa7w/5wK30rAY2A=,tag:PqyVnQ8bfClMgmHqS+B1Zw==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:J687ysTIaoi1PKWF4V4y+v0uGQ==,iv:GJEmF8itP7JRLq7N1vlQVk9bGlnGUJGSlFzlT6uDiIU=,tag:87KELNH8vK/pIUMVtKXZNQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:81rjyV4KZDbNJ9DJ9JL6KgPXjzm1,iv:+UaEGxXcWKRzsi96sSn92qHcmAuHdr9bVGnKF3Ykb9w=,tag:xHwMceDmyAiVWkO0mNEkMA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:mhajKggKoDF4fT05qmSLKiSF0Q==,iv:eMiRQsC4O0eOJcJCveoniJNTY8ERSfHioCYuecqh8b4=,tag:d9Y9Seqmmhi6t6wUtQetfw==,type:str]
    #ENC[AES256_GCM,data:eZWBevU=,iv:CmyVZgTfkwrnyq2UnHtdk4lYtgVx6qTJr4k2Jh/YHSk=,tag:qgTfyUhTp08+ziZyFokxmA==,type:comment]
    LDAP_AUTH_ENABLED: ENC[AES256_GCM,data:87kjQA==,iv:nu4myAYuEedj6J4w8lyz0u5SYMFVnUr/IswwLa4hRq4=,tag:fPh4hrYkij7iK7ECks3jMw==,type:str]
    LDAP_SERVER_URL: ENC[AES256_GCM,data:GQBRU62RdxW47yT14G9KJc+uGHl2B/u8TlMGrqODoto0EPCwmHVHDw==,iv:K2V4DOHQcxhIw97x19y2+WJAv3o1RPSWswEXiFPER1Q=,tag:x0Arj1CY0ENb51ZU8TSVwA==,type:str]
    LDAP_TLS_INSECURE: ENC[AES256_GCM,data:0a3gYQ==,iv:v90wbaAa7iuigPG6V4LOTapF5wE//tiaQ5I6Eh7mVeU=,tag:dn4lTze05XsGz051c4vM/w==,type:str]
    LDAP_BASE_DN: ENC[AES256_GCM,data:wTboWQZmfC1Q5+Iz3+3okDsoDGIcf/gK5g==,iv:9VbSCfYmM8uOCpmIyLqWdejLLWudeBqRKyAJkujYmZU=,tag:TKtZ4LeceoHRLAtk2dFpHw==,type:str]
    LDAP_QUERY_BIND: ENC[AES256_GCM,data:qxFGyzlb5RuzQ74K1pM2R0uFtW9xtDPskGXXQBznJj/noTJxa0LlyC0J,iv:NMRg+gCzRyiSrdDRqMkTDgwBFFNVUAvyThvKAQEg1DI=,tag:RSUjnnTa8mnhuw1Y69OMFg==,type:str]
    LDAP_QUERY_PASSWORD: ENC[AES256_GCM,data:08zjLN/wNUh9X7iFpPGd87Cfzlx+twhKC8ywmyAEubKA,iv:BP0HAjoc7la+DZhebF4VPGdD1xtc3OeQ610e0Ak+ixg=,tag:HTjAG0+MY6BoRWUuTxvOiQ==,type:str]
    LDAP_USER_FILTER: ENC[AES256_GCM,data:/14moXZXlxVkE55auJUmTlDMx/SgA+2Nkwbvvs5hx6KMZPbkzJlSVolwhlTV,iv:Vfla8oidBddTcWR2cNUuC6AJjHFJftfytF/eB1ZMt44=,tag:5lF3PVvc6hk6+mrCStYYzw==,type:str]
    LDAP_ADMIN_FILTER: ENC[AES256_GCM,data:30Yy+C+5sEVIOrb61ayHcC4eJe7BsJlfpGAc0PnkWRlWh/jLNq2ApP15JSmvvU72pGs=,iv:HT7feokugre2irzDFcl987+EaIQtePsQwvghWL+onxA=,tag:XTh+hUn8HUqqwDq00y6/Vg==,type:str]
    LDAP_ID_ATTRIBUTE: ENC[AES256_GCM,data:O06b,iv:cBjDTpaX3RTJWpLVdpCjFcSGCbuOXVId/bPQ5a4CmCY=,tag:PmtO8PuHYxPjDpHB1LadxQ==,type:str]
    LDAP_NAME_ATTRIBUTE: ENC[AES256_GCM,data:QaSJg+JhXbHlXPw=,iv:ROukEu9FcrW0Ju54wb91118ZBqrx1Ag01DH7hwNO07c=,tag:9/JsU0hQX5RkD0HrtCjSog==,type:str]
    LDAP_MAIL_ATTRIBUTE: ENC[AES256_GCM,data:wh7z3g==,iv:MlRlChjMNodH70OyNdfG5VZ8f7qqUT3vEWNI6psiRWo=,tag:zja6+gRioQ61nO+qvQnIOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ke0cxfxawre9ps0d2h0ez43um25qk4gk6wfdg9s8a28pmxwlmcdqtwekph
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYUtZOFpHWWNjYitONTdI
            elRoVk1icE8wU0svcmY4b1lPY2dNMFh6d1hZCllUT2wyZmFDVng3a3ljemQ0VjRO
            R1hteWNUZmpDMi9HMUt4TnpsRUVCUFEKLS0tIHZxVWpUUytiVGp3cHBEa0l4enlF
            MmgwamlSeDhQZy9uYWNvNVhvNUMwRW8KiFDM5UUjZ0KC7uFmBMISCES7VQQ3JJcy
            SltXcCfKRgwPKEqikB/jmoL1MlhVaqKoLum/1tpHOD1QKKYS8In2iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T01:14:33Z"
    mac: ENC[AES256_GCM,data:LBcqKOsHWHXm4/c0ctUDoZzqya+asmmXVj4YGx7gIj3jnmZXUdvX/0Je+UTOZPKfyoXVNvASywsRGmG5W9dP6H5kiTpwxT96H2D4WtgnWsDjvO0dK3JZ3puUTQPYgTuHMy2Mb+vSnU31OpDAjb8aOCy+KL7BwYvhChUXFZlgqfY=,iv:gHF0G2D0AshQjlgY0QvveemmgxMTrix6HdC+2d1p274=,tag:BKDpq+92Gbu8xhoqPJmxaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
