---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app changedetection
  namespace: flux-system
spec:
  targetNamespace: self-hosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/self-hosted/changedetection/app
  dependsOn:
    - name: longhorn
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      APP_UID: "2000"
      APP_GID: "2000"
      CAPACITY: 5Gi
      GATUS_SUBDOMAIN: *app
