---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
  namespace: flux-system
spec:
  targetNamespace: self-hosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/self-hosted/mealie/app"
  prune: true
  dependsOn:
    - name: longhorn
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: mealie
      CAPACITY: 10Gi
