---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
spec:
  accessModes: ["${ACCESSMODES:-ReadWriteOnce}"]
  resources:
    requests:
      storage: "${CAPACITY:-5Gi}"
  storageClassName: "${STORAGECLASS:-longhorn}"
